"""your next change

Revision ID: 5309b12bccd8
Revises: aecb1015f741
Create Date: 2025-11-19 22:39:44.267930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5309b12bccd8'
down_revision: Union[str, None] = 'aecb1015f741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', name='meeting_room_status'), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_rooms_host_id'), 'meeting_rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_meeting_rooms_room_code'), 'meeting_rooms', ['room_code'], unique=True)
    op.create_table('meeting_participants',
    sa.Column('meeting_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_user', sa.Enum('host', 'co_host', 'participant', name='meeting_participant_role'), server_default='participant', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('joined', 'left', 'kicked', name='meeting_participant_status'), server_default='joined', nullable=False),
    sa.CheckConstraint('left_at IS NULL OR joined_at <= left_at', name='ck_meeting_participants_time_order'),
    sa.ForeignKeyConstraint(['meeting_room_id'], ['meeting_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_room_id', 'user_id'),
    sa.UniqueConstraint('meeting_room_id', 'user_id', name='uq_meeting_participants_room_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_rooms_room_code'), table_name='meeting_rooms')
    op.drop_index(op.f('ix_meeting_rooms_host_id'), table_name='meeting_rooms')
    op.drop_table('meeting_rooms')
    # ### end Alembic commands ###
