"""Tăng độ dài room_code

Revision ID: 5e9a25bddaec
Revises: eed384adbc52
Create Date: 2026-01-16 14:35:55.477534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9a25bddaec'
down_revision: Union[str, None] = 'eed384adbc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_meeting_participants_room_user', 'meeting_participants', ['meeting_room_id', 'user_id'])
    op.alter_column('meeting_rooms', 'room_code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_rooms', 'room_code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint('uq_meeting_participants_room_user', 'meeting_participants', type_='unique')
    # ### end Alembic commands ###
