"""fix

Revision ID: aecb1015f741
Revises: a467b4c23aee
Create Date: 2025-11-19 22:27:11.617865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecb1015f741'
down_revision: Union[str, None] = 'a467b4c23aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_meeting_participants_room_user', 'meeting_participants', ['meeting_room_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_meeting_participants_room_user', 'meeting_participants', type_='unique')
    # ### end Alembic commands ###
